import './globals.css'
import { Inter } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { Suspense } from 'react'


import Navbar from '@/components/navbar'
import Loading from './loading.js'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className} >
          <Navbar />
            
          <Suspense fallback={<Loading />} >
            <div className={'container mx-auto '}>{children}</div>
          </Suspense>

        </body>
      </UserProvider>
    </html>
  )
}
